FROM maven:alpine AS MAVEN_TOOL_CHAIN
WORKDIR /tmp
COPY pom.xml ./
COPY src ./src
RUN mvn package

FROM bitnami/google-cloud-sdk as gcloud

#FROM python:3.9-slim
FROM alpine:latest
RUN apt-get update 
RUN apt-get install -y \
    openjdk-11-jre \
    git \
    bash \
    curl \
    openssh-client \
    libssl-dev 

COPY --from=MAVEN_TOOL_CHAIN /tmp/target/spring-boot-perfkit-1.0.0-SNAPSHOT.jar /tmp/
COPY src/main/resources/application.properties /tmp/
COPY benchmark.sh /tmp/

RUN cd $HOME \
  && git clone https://github.com/prakhag2/PerfKitBenchmarker \
  && pip3 install -r $HOME/PerfKitBenchmarker/requirements.txt

#RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz \
#  && mkdir -p /usr/local/gcloud \
#  && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
#  && /usr/local/gcloud/google-cloud-sdk/install.sh \
#  && \rm -rf /tmp/*.tar.gz
COPY --from=gcloud /opt/bitnami/google-cloud-sdk/ /usr/local/gcloud/google-cloud-sdk
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

WORKDIR /tmp
RUN chmod +x /tmp/benchmark.sh
CMD ["java","-jar","spring-boot-perfkit-1.0.0-SNAPSHOT.jar", "--spring.config.location=file:application.properties"]

