aerospike:
  description: Runs Aerospike.
  flags:
    # Duration of each test iteration in secs.
    aerospike_benchmark_duration: 60

    # The number to increase the Aerospike client threads per vm by for each iteration of the test.
    aerospike_client_threads_step_size: 8

    # Number of aerospike_server processes to run. e.g. if this is set to 2, we will launch 2 aerospike processes on the same VM.
    # Flags such as aerospike_num_keys and client threads will be applied to each instance.
    aerospike_instances: 1

    # The maximum number of Aerospike client threads per vm.
    aerospike_max_client_threads: 128

    # The minimum number of Aerospike client threads per vm.
    aerospike_min_client_threads: 8

    # The number of keys to load Aerospike with. The index must fit in memory regardless of where the actual data is being stored and each entry in the index requires 64 bytes.
    aerospike_num_keys: 1000000

    # Whether or not to publish one sample per aggregationwindow with histogram. By default, only TimeSeries sample will be generated.
    aerospike_publish_detailed_samples: false

    # The percent of operations which are reads.
    aerospike_read_percent: 90

    # Dynamically adjust act test load. We start at initial load from --act_load, if the underlying driver not able to keep up, reduce the load and retry.
    act_dynamic_load: false

    # Stop the benchmark when completing current load. This can be useful deciding maximum sustained load for stress tests.
    act_stop_on_complete: true

    # Replication factor for aerospike server.
    aerospike_replication_factor: 1

    # Number of threads per transaction queue.
    aerospike_service_threads: 4

    # <memory|disk>: The type of storage to use for Aerospike data. The type of disk is controlled by the "data_disk_type" flag.
    aerospike_storage_type: memory

  # Client and Server VM configurations
  vm_groups:
    workers:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-b
          image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20220927
          boot_disk_size: 50
      vm_count: 1
      disk_spec:
        GCP:
          disk_size: 50
          disk_type: pd-ssd
    clients:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-b
          image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20220927
          boot_disk_size: 50
      vm_count: 1
      disk_spec:
        GCP:
          disk_size: 50
          disk_type: pd-ssd
