mongodb_ycsb:
  description: Run YCSB against a single MongoDB node.
  flags:
    # Configure block device readahead settings.
    #mongodb_readahead_kb:

    # MongoDB write concern.
    mongodb_writeconcern: acknowledged

  # Client and Server VM configurations
  vm_groups:
    workers:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-b
          image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20220927
          boot_disk_size: 50
      vm_count: 1
      disk_spec:
        GCP:
          disk_size: 50
          disk_type: pd-ssd
    clients:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-b
          image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20220927
          boot_disk_size: 50
      vm_count: 1
      disk_spec:
        GCP:
          disk_size: 50
          disk_type: pd-ssd
