redis_memtier:
  description: Run memtier_benchmark against Redis.
  flags:
    # If true, measure cpu usage on the server via
    # top tool. Defaults to False.
    redis_memtier_measure_cpu: false

    # <noeviction|allkeys-lru|volatile-lru|allkeys-
    # random|volatile-random|volatile-ttl>: Redis eviction policy when maxmemory
    # limit is reached. This requires running clients with larger amounts of data
    # than Redis can hold.
    redis_eviction_policy: noeviction

    # If true, uses the default redis snapshot policy.
    redis_server_enable_snapshots: false

    # Only supported for redis version >= 6, the number
    # of redis server IO threads to use.
    redis_server_io_threads: 4

    # If true, attempts to pin IO threads to CPUs.
    redis_server_io_threads_cpu_affinity: false

    # If true, makes both reads and writes
    # use IO threads instead of just writes.
    redis_server_io_threads_do_reads: false

    # Version of redis server to use.
    redis_server_version: 7.0.3

    # If true, simulate usage of disks on the server for aof backups.
    redis_simulate_aof: false

    # Total number of redis server processes. Useful
    # when running with a redis version lower than 6.
    redis_total_num_processes: 1

  # Client and Server VM configurations
  vm_groups:
    servers:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-b
          image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20220927
          boot_disk_size: 50
      vm_count: 1
      disk_spec:
        GCP:
          disk_size: 50
          disk_type: pd-ssd
    clients:
      vm_spec:
        GCP:
          machine_type: n1-standard-1
          zone: us-central1-b
          image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20220927
          boot_disk_size: 50
      vm_count: 1
      disk_spec:
        GCP:
          disk_size: 50
          disk_type: pd-ssd
